/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_distributedea_problems_continuousoptimalization_bbobv1502_BbobJNI */

#ifndef _Included_org_distributedea_problems_continuousoptimalization_bbobv1502_BbobJNI
#define _Included_org_distributedea_problems_continuousoptimalization_bbobv1502_BbobJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_BbobJNI
 * Method:    initialize
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_BbobJNI_initialize
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_BbobJNI
 * Method:    evaluate
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_BbobJNI_evaluate
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_BbobJNI
 * Method:    finalizee
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_BbobJNI_finalizee
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
