/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric */

#ifndef _Included_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric
#define _Included_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric
 * Method:    initBBOB
 * Signature: (IIILjava/lang/String;Lorg/distributedea/problems/continuousoptimalization/bbobv1502/JNIfgeneric/Params;)D
 */
JNIEXPORT jdouble JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_initBBOB
  (JNIEnv *, jobject, jint, jint, jint, jstring, jobject);

/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric
 * Method:    exitBBOB
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_exitBBOB
  (JNIEnv *, jobject);

/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric
 * Method:    exist
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_exist
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric
 * Method:    getFtarget
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_getFtarget
  (JNIEnv *, jobject);

/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric
 * Method:    getBest
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_getBest
  (JNIEnv *, jobject);

/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric
 * Method:    getFbest
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_getFbest
  (JNIEnv *, jobject);

/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric
 * Method:    getEvaluations
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_getEvaluations
  (JNIEnv *, jobject);

/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric
 * Method:    setNoiseSeed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_setNoiseSeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric
 * Method:    unif
 * Signature: ([DII)V
 */
JNIEXPORT void JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_unif
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric
 * Method:    evaluate
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_evaluate
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_Params */

#ifndef _Included_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_Params
#define _Included_org_distributedea_problems_continuousoptimalization_bbobv1502_JNIfgeneric_Params
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
